// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHQGP34X4ZqV3z_PHaXXCLryGg2FM05dw',
    appId: '1:602242504044:web:40e4e6d491866f6f56cf49',
    messagingSenderId: '602242504044',
    projectId: 'college101-d1876',
    authDomain: 'college101-d1876.firebaseapp.com',
    storageBucket: 'college101-d1876.appspot.com',
    measurementId: 'G-F3B839JD0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBekRvG4Oo9T-3bdJD6TsBfxTBEUsVgs8Q',
    appId: '1:602242504044:android:eab452af8088aa3156cf49',
    messagingSenderId: '602242504044',
    projectId: 'college101-d1876',
    storageBucket: 'college101-d1876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh8g6lo6LhJ5zwoLqgGRP140vvjpTcUro',
    appId: '1:602242504044:ios:23f1549cbb1c708e56cf49',
    messagingSenderId: '602242504044',
    projectId: 'college101-d1876',
    storageBucket: 'college101-d1876.appspot.com',
    androidClientId: '602242504044-214398pv2vtrr4jqnk8ku104kvsuhfpm.apps.googleusercontent.com',
    iosClientId: '602242504044-d09pil1i2a0eit198j9a1bqvq7k62837.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackTj23',
  );
}
